
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar &
# exec-once = waybar & hyprpaper & firefox


# starting Swaync everyting hyprland runs 
exec-once = swaync



# from cliphist
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


# vivaldi browser Autostart
exec-once = vivaldi-stable --ozone-platform=x11
