
#############
### INPUT ###
#############

# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
   kb_layout = us
  kb_options = ctrl:nocaps # ctrl swapped with caps  
# kb_model = 
# Kb_rules = 
# kb_variant = 
  # Change speed of keyboard repeat
  # very useful for vim /emacs (default 30 , 600 ) 
  repeat_rate = 90
  repeat_delay = 300


  # This was in orginal conf but i have no idea about this option 
  # follow_mouse = 1 

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true 

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
# This was orignally set to false and turned to this value  by me 
# if there are 3 and 9 open and in use it will go to them without the ones in between (because they are not active at all )
gestures {
    workspace_swipe = true 
}

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}



# Scroll faster in the terminal
# windowrule = scrolltouchpad 1.5, class:Alacritty

