
#############
### INPUT ###
#############

# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
   kb_layout = us
  kb_options = ctrl:nocaps # ctrl swapped with caps
# kb_model =
# Kb_rules =
# kb_variant =
  # Change speed of keyboard repeat
  # very useful for vim /emacs (default 30 , 600 )
  repeat_rate = 70
  repeat_delay = 300


  # This was in orginal conf but i have no idea about this option
  # follow_mouse = 1

  # Increase sensitity for mouse/trackpack (default: 0)
   sensitivity = 0.6

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.7
  }
}


################
### GESTURES ###
################

# https://wiki.hypr.land/0.54.0/Configuring/Gestures/
# gesture = fingers , direction , action , options

# Use this to switch workspaces with three finger side to side swipe
gesture = 3, horizontal, workspace


# Toggle whirs with four fingers down
gesture = 4 , down , dispatcher  , exec , /home/bi/.local/bin/whisrs toggle


# gesture = 4, up, special, scratchpad
gesture = 4, up, dispatcher , togglespecialworkspace , magic

# Volume up and down if needed (using another script in waybar for this rn)
# gesture = 4, down, dispatcher, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
# gesture = 4, up, dispatcher, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+

# Four-finger swipe left/right for play/pause
gesture = 4, left, dispatcher, exec, playerctl play-pause
gesture = 4, right, dispatcher, exec, playerctl play-pause









####################
### PER-DEVICE ###
####################

# Example per-device config
# See https:3/wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}



##################
### TERMINAL ###
##################

# Scroll faster in the terminal
# windowrule = scrolltouchpad 1.5, class:Kitty
