
#############
### INPUT ###
#############

# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
   kb_layout = us
  kb_options = ctrl:nocaps # ctrl swapped with caps
# kb_model =
# Kb_rules =
# kb_variant =
  # Change speed of keyboard repeat
  # very useful for vim /emacs (default 30 , 600 )
  repeat_rate = 60
  repeat_delay = 230


  # This was in orginal conf but i have no idea about this option
  # follow_mouse = 1

  # Increase sensitity for mouse/trackpack (default: 0)
   sensitivity = 0.75
  touchpad {
    # Use natural (inverse) scrolling
     natural_scroll = false 

    # Use two-finger clicks for right-click instead of lower-right corner
    clickfinger_behavior = 1

    # Control the speed of your scrolling
    scroll_factor = 0.7




    # Behaviour of left and right click with two fingers
    # See https://wiki.hyprland.org/Configuring/Keywords/#two-finger-clicks
    # clickfinger_behavior = single
    # clickfinger_behavior = double
    # clickfinger_behavior = single_right
    # clickfinger_behavior = double_right
    
    clickfinger_behavior = true >


    # i Saw this on reddit and sometimes the way i rest my hands can end up in unwanted activations so i will keep this on for now 
    disable_while_typing = true 
  }

 

}



##############
### Devices ###
##############
# You can do this for any device 
# Doing this for touchpad here

device  {
name = "elan0712:00-04f3:30fd-touchpad"
      # Use natural scrollin/g
      natural_scroll = true 

      # This  is arbitrary
       sensitivity = -0.5

      # Better mouse acceleration
      accel_profile = flat 

      # Changing the scroll factor
      scroll_factor = 0.8

      # Behaviour of left and right click with two fingers
      clickfinger_behavior = 1

      # Disabhle while typing 
      disable_while_typing = true
          
  
}



   
################
### GESTURES ###
################>

# Gestures available
# swipe	any swipe
# horizontal	horizontal swipe
# vertical	vertical swipe
# left, right, up, down	swipe directions
# pinch	any pinch
# pinchin, pinchout	directional pinch

# https://wiki.hypr.land/0.54.0/Configuring/Gestures/
# gesture = fingers , direction , action , options

# Use this to switch workspaces with three finger side to side swipe
gesture = 3, horizontal, workspace


# Toggle whirs with four fingers down
gesture = 4 , down , dispatcher  , exec , /home/bi/.local/bin/whisrs toggle


# gesture = 4, up, special, scratchpad
gesture = 4, up, dispatcher , togglespecialworkspace , magic



# Use flameshot to take a screenshot and paste it to clipboard
gesture = 4, pinchout, dispatcher, exec, flameshot gui --clipboard

 # Using 3 Fingers pinchin to play/pause media using dispatcher and playerctl in hyprland 
 gesture = 4 , pinchin , dispatcher , exec , playerctl play-pause


# Volume keys Contorl the positon of mpris  using four fingers horizontal swipe 
 gesture = 4, right, dispatcher, exec, playerctl position 5+
 gesture = 4, left, dispatcher, exec, playerctl position 5-


# Using 4 fingers with shift to go to next/previous track
gesture = 4, right, mod:SHIFT, dispatcher, exec, playerctl next
gesture = 4, left, mod:SHIFT, dispatcher, exec, playerctl previous


# using 3 Fingers with SUPER Key to close windows 
gesture = 3 , down , mod:SUPER , dispatcher , killactive 

# Using SUPER and three fingers uo to toggle hide waybar script to get full screen real estate back 
gesture = 3 , up , mod:SUPER , dispatcher , exec , /home/bi/dotfiles/.config/hypr/scripts/toggle-waybar.sh




##################
### TERMINAL ###
##################

# Scroll faster in the terminal
# windowrule = scrolltouchpad 1.5, class:Kitty
